version: "3.7"
services:
  db:
    build:
      context: ../docker
      dockerfile: Dockerfile_MySQL_Apache
    image: "mysql:latest"
    ports: 
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "database_dir:/var/lib/mysql"
  wp:
    depends_on:
      - db
    build: 
      context: ../docker
      dockerfile: Dockerfile_Wordpress
    image: "wordpress:php7.4-apache"
    ports:
      - "8900:80"
      - "9004:9003"
    restart: always
    environment: 
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - "wp_dir:/var/www/html"
    extra_hosts:
#      - "wp.docker.internal:172.18.0.3" 
      - "host.docker.internal:host-gateway"
    container_name: wp

volumes:
  wp_dir:
  database_dir:
